export class StaffClass {
    academicPaper: string;
    address: number;
    age: number;
    award: string;
    beginWorkTime: Date;
    birthDate: Date;
    computerDegree: string;
    country: string;
    deptId: number;
    disability: number;
    duty: string;
    educatExp: string;
    email: string;
    emgcyContact: string;
    emgcyContactPhone: string;
    engDegree: number;
    gender: number;
    graduateTime: Date;
    highestDegree: number;
    highestMajor: string;
    hkmt: number;
    id: number;
    joinTime: Date;
    mandarinDegree: number;
    maritalStatus: number;
    nationality: string;
    offJobTime: Date;
    officeAddressId: number;
    officePhone: string;
    partTimeDuty: string;
    passNumber: string;
    passType: number;
    phone: string;
    politicalStatus: number;
    qqWechart: string;
    schoolId: number;
    schoolTag: string;
    secMajor: string;
    staffAttribute: number;
    staffCode: string;
    staffName: string;
    status: number;
    studyAbroad: number;
    teacherCert: number;
    title: string;
    workExp: string;
    schoolName: string;
    staffAttrName: string;
    deptName: string;
    addr1: string;
    addr2: string;
    constructor() {
        this.academicPaper = "";
        this.address = 0;
        this.age = 0;
        this.award = "";
        this.beginWorkTime = new Date();
        this.birthDate = new Date();
        this.computerDegree = "";
        this.country = "";
        this.deptId = 0;
        this.disability = 0;
        this.duty = "";
        this.educatExp = "";
        this.email = "";
        this.emgcyContact = "";
        this.emgcyContactPhone = "";
        this.engDegree = 0;
        this.gender = 0;
        this.graduateTime = new Date();
        this.highestDegree = 0;
        this.highestMajor = "";
        this.hkmt = 0;
        this.id = 0;
        this.joinTime = new Date();
        this.mandarinDegree = 0;
        this.maritalStatus = 0;
        this.nationality = "";
        this.offJobTime = new Date();
        this.officeAddressId = 0;
        this.officePhone = "";
        this.partTimeDuty = "";
        this.passNumber = "";
        this.passType = 0;
        this.phone = "";
        this.politicalStatus = 0;
        this.qqWechart = "";
        this.schoolId = 0;
        this.schoolTag = "";
        this.secMajor = "";
        this.staffAttribute = 0;
        this.staffCode = "";
        this.staffName = "";
        this.status = 0;
        this.studyAbroad = 0;
        this.teacherCert = 0;
        this.title = "";
        this.workExp = "";
        this.schoolName = "";
        this.staffAttrName = "";
        this.deptName = "";
        this.addr1 = "";
        this.addr2 = "";
    }
}
